laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['web', 'auth'], 'prefix' => ''], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('types', 'TypeController');
    Route::resource('users', 'UserController');
    Route::resource('projects', 'ProjectController');
    Route::get('contact', 'ContactController@create');
    Route::post('contact', 'ContactController@store');
});


Route::get('/home', 'HomeController@index')->name('home');

laravel/app/Http/Controllers/TypeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Type;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;


/**
 * Class TypeController
 * @package App\Http\Controllers
 */
class TypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userConnected = Auth::user();

        $types = Type::paginate();

        return view('type.index', compact('userConnected','types'))
            ->with('i', (request()->input('page', 1) - 1) * $types->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = new Type();
        return view('type.create', compact('type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Type::$rules);

        $type = Type::create($request->all());

        Alert::success('Type created', 'Successfully');

        return redirect()->route('types.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $type = Type::find($id);

        return view('type.show', compact('type'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $type = Type::find($id);

        return view('type.edit', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Type $type
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Type $type)
    {
        request()->validate(Type::$rules);

        $type->update($request->all());

        Alert::success('Type edited', 'Successfully');


        return redirect()->route('types.index');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $type = Type::find($id)->delete();

        return redirect()->route('types.index')
            ->with('success', 'Type deleted successfully');
    }
}

laravel/resources/views/type/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Type
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Type</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('types.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('type.form')

                        </form>
                        <br />
                        <a class="btn btn-info" href="{{ route('types.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

laravel/resources/views/type/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Type
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Type</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('types.update', $type->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('type.form')

                        </form>
                        <br />
                        <a class="btn btn-info" href="{{ route('types.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

laravel/resources/views/type/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('name') }}
            {{ Form::text('name', $type->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Name']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

laravel/resources/views/type/index.blade.php
@extends('layouts.app')

@section('template_title')
    Type
@endsection

@section('content')
    <div class="container-fluid">
        @can('isAdmin')
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Type') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('types.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>No</th>
										<th>Name</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($types as $type)
                                        <tr>
                                            <td>{{ ++$i }}</td>
											<td>{{ $type->name }}</td>
                                            <td>
                                                <form action="{{ route('types.destroy',$type->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('types.show',$type->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('types.edit',$type->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
{{--                                                    La suppression est temporairement indisponible--}}
{{--                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>--}}
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-center">
                    {!! $types->links() !!}
                </div>
            </div>
        </div>
        @endcan
        @if (auth()->user()->can('isCustomer') || auth()->user()->can('isDebugger'))
            <div class="container mt-5 mb-5">
                <a class="btn btn-info" href="{{ route('home') }}"> Back HOME</a>
            </div>
        @endif
    </div>
@endsection

laravel/resources/views/type/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $type->name ?? 'Show Type' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Type</span>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Name :</strong>
                            {{ $type->name }}
                        </div>
                        <a class="btn btn-info" href="{{ route('types.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection