laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::group(['middleware' => ['web', 'auth'], 'prefix' => ''], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('types', 'TypeController');
    Route::resource('users', 'UserController');
    Route::resource('projects', 'ProjectController');
    Route::get('contact', 'ContactController@create');
    Route::post('contact', 'ContactController@store');
});


Route::get('/home', 'HomeController@index')->name('home');

laravel/app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Task
 *
 * @property $id
 * @property $state
 * @property $description
 * @property $customer_id
 * @property $debugger_id
 * @property $type_id
 * @property $project_id
 * @property $created_at
 * @property $updated_at
 *
 * @property Project $project
 * @property Type $type
 * @property User $users
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Task extends Model
{

    static $rules = [
		'state' => 'required',
		'description' => 'required',
		'customer_id' => 'required',
		'debugger_id' => 'nullable',
		'type_id' => 'required',
		'project_id' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['state','description','customer_id','debugger_id','type_id','project_id'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function project()
    {
        return $this->hasOne('App\Models\Project', 'id', 'project_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function type()
    {
        return $this->hasOne('App\Models\Type', 'id', 'type_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'customer_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function users()
    {
        return $this->hasOne('App\Models\User', 'id', 'debugger_id');
    }


}

laravel/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Models\Task;
use App\Models\Type;
use App\Models\User;
use Illuminate\Support\Facades\Mail;
use App\Mail\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

/**
 * Class TaskController
 * @package App\Http\Controllers
 */
class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userConnected = Auth::user();

        $tasks = Task::all();
        $users = User::all()->pluck('name', 'id');
        $types = Type::all()->pluck('name', 'id');
        $projects = Project::all()->pluck('name', 'id');

        return view('task.index', compact('userConnected','tasks', 'users', 'types', 'projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $userConnected = Auth::user();
        $userID = $userConnected->id;

        $task = new Task();
        $users = User::all()->pluck('name', 'id');
        $userConnectedName = User::all()->where('customer_id', $userID);
        $types = Type::all()->pluck('name', 'id');
        if ($userConnected->role == 'customer') {
            $projects = Project::all()->where('customer_id', $userID)->pluck('name', 'id');
        } else{
            $projects = Project::all()->pluck('name', 'id');
        }

        return view('task.create', compact('userConnectedName','task', 'users', 'types', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Task::$rules);

        $task = Task::create($request->all());
        $state = $task->state;

        if ($state == 'new') {
            Mail::to('administrateur@chezmoi.com')
            ->send(new Contact($request->except('_token'), $task));
        }


        Alert::success('Task created', 'Successfully');

        return redirect()->route('home')
            ->with('success', 'Task created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::find($id);
        $users = User::all()->pluck('name', 'id');
        $types = Type::all()->pluck('name', 'id');
        $projects = Project::all()->pluck('name', 'id');

        return view('task.show', compact('task', 'users', 'types', 'projects'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);
        $users = User::all()->pluck('name', 'id');
        $types = Type::all()->pluck('name', 'id');
        $projects = Project::all()->pluck('name', 'id');

        return view('task.edit', compact('task', 'users', 'types', 'projects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Task $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        request()->validate(Task::$rules);

        $task->update($request->all());

        Alert::success('Task created', 'Successfully');

        return redirect()->route('home');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $task = Task::find($id)->delete();

        return redirect()->route('tasks.index')
            ->with('success', 'Task deleted successfully');
    }
}

laravel/resources/views/task/create.blade.php
@extends('layouts.app')
@section('template_title')
    Create Task
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Task</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('tasks.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('task.form')

                        </form>
                        <br />
                        @can('isCustomer')
                            <a class="btn btn-info" href="{{ route('home') }}"> Back</a>
                        @endcan
                        @if (auth()->user()->can('isAdmin') || auth()->user()->can('isDebugger'))
                            <a class="btn btn-info" href="{{ route('tasks.index') }}"> Back</a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

laravel/resources/views/task/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Task
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Task</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('tasks.update', $task->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('task.form')

                        </form>
                        <br />
                        <a class="btn btn-info" href="{{ route('tasks.index') }}"> Back</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

laravel/resources/views/task/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">

        <div class="form-group">
            {{ Form::hidden('state', 'new') }}
        </div>
        <div class="form-group">
            {{ Form::label('description') }}
            {{ Form::textarea('description', $task->description, ['class' => 'form-control' . ($errors->has('description') ? ' is-invalid' : ''), 'placeholder' => '']) }}
            {!! $errors->first('description', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        @can('isCustomer')
            <div class="form-group">
                {{ Form::hidden('customer_id', Auth::user()->id) }}
            </div>
        @endcan
        @if (auth()->user()->can('isAdmin') || auth()->user()->can('isDebugger'))
            <div class="form-group">
                {{ Form::label('customer_id', 'Customer') }}
                {{ Form::select('customer_id', $users, $task->customer_id, ['class' => 'form-control' . ($errors->has('customer_id') ? ' is-invalid' : ''), 'placeholder' => '']) }}
                {!! $errors->first('customer_id', '<div class="invalid-feedback">:message</p>') !!}
            </div>
        @endif
        @can('isAdmin')
            <div class="form-group">
                {{ Form::label('debugger_id', 'Debugger') }}
                {{ Form::select('debugger_id', $users, $task->debugger_id, ['class' => 'form-control' . ($errors->has('debugger_id') ? ' is-invalid' : ''), 'placeholder' => '']) }}
                {!! $errors->first('debugger_id', '<div class="invalid-feedback">:message</p>') !!}
            </div>
        @endcan
        @can('isDebugger')
            <div class="form-group">
                {{ Form::label('debugger_id', 'Debugger') }}
                {{ Form::select('debugger_id', $users, Auth::user()->id, ['class' => 'form-control' . ($errors->has('debugger_id') ? ' is-invalid' : ''), 'placeholder' => '']) }}
                {!! $errors->first('debugger_id', '<div class="invalid-feedback">:message</p>') !!}
            </div>
        @endcan
        <div class="form-group">
            {{ Form::label('type_id', 'Type') }}
            {{ Form::select('type_id',$types, $task->type_id, ['class' => 'form-control' . ($errors->has('type_id') ? ' is-invalid' : ''), 'placeholder' => '']) }}
            {!! $errors->first('type_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('project_id', 'Project') }}
            {{ Form::select('project_id', $projects, $task->project_id, ['class' => 'form-control' . ($errors->has('project_id') ? ' is-invalid' : ''), 'placeholder' => '']) }}
            {!! $errors->first('project_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

laravel/resources/views/task/index.blade.php
@extends('layouts.app')
@section('template_title')

@endsection

@section('content')
    <div class="container-fluid">
        @if (auth()->user()->can('isAdmin') || auth()->user()->can('isDebugger'))
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <h3 id="card_title">
                                {{ __('Task') }}
                            </h3>

                            <div class="float-right">
                                <a href="{{ route('tasks.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                    {{ __('Create New') }}
                                </a>
                            </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="table_tasks" class="table table-striped table-hover  table-sm">
                                <thead class="thead-dark">
                                <tr class="d-flex">
                                    <th class="col-1">State</th>
                                    <th class="col-4">Description</th>
                                    <th class="col-2">Customer</th>
                                    <th class="col-1">Debugger</th>
                                    <th class="col-1">Type</th>
                                    <th class="col-2">Project</th>
                                    <th class="col-1">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($tasks as $task)
                                    <tr class="d-flex">
                                        <td class="col-1">{{ $task->state }}</td>
                                        <td class="col-3">{{ $task->description }}</td>
                                        <td class="col-1">{{ $task->user->name }}</td>
                                        <td class="col-1">{{ $task->users->name ?? ''}}</td>
                                        <td class="col-1">{{ $task->type->name }}</td>
                                        <td class="col-2">{{ $task->project->name }}</td>
                                        <td class="col-1">
                                            <form action="{{ route('tasks.destroy',$task->id) }}" method="POST">
                                                <a class="btn btn-sm btn-primary " href="{{ route('tasks.show',$task->id) }}"><i class="fa fa-fw fa-eye"></i></a>
                                                <a class="btn btn-sm btn-success" href="{{ route('tasks.edit',$task->id) }}"><i class="fa fa-fw fa-edit"></i></a>
                                            @can('isAdmin')
                                                @csrf
                                                @method('DELETE')
{{--                                                la suppression est temporairement indisponible--}}
{{--                                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i></button>--}}
                                            @endcan
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @else
            @can('isCustomer')
                <div class="container mt-5 mb-5">
                    <a class="btn btn-info" href="{{ route('home') }}"> Back HOME</a>
                </div>
            @endcan
        @endif
    </div>
@endsection

laravel/resources/views/task/show.blade.php
@extends('layouts.app')
@section('template_title')
    {{ $task->name ?? 'Show Task' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <h3 class="card-title">Show Task</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <strong>State :</strong>
                            {{ $task->state }}
                        </div>
                        <div class="form-group">
                            <strong>Description :</strong>
                            {{ $task->description }}
                        </div>
                        <div class="form-group">
                            <strong>Customer :</strong>
                            {{ $task->user->name}}
                        </div>
                        <div class="form-group">
                            <strong>Debugger :</strong>
                            {{ $task->users->name ?? ''}}
                        </div>
                        <div class="form-group">
                            <strong>Type :</strong>
                            {{ $task->type->name }}
                        </div>
                        <div class="form-group">
                            <strong>Project :</strong>
                            {{ $task->project->name }}
                        </div>
                        @can('isCustomer')
                            <a class="btn btn-info" href="{{ route('home') }}"> Back</a>
                        @endcan
                        @if (auth()->user()->can('isAdmin') || auth()->user()->can('isDebugger'))
                            <a class="btn btn-info" href="{{ route('tasks.index') }}"> Back</a>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection